import {
  CategoryDTO,
  ProductDTO,
  OrderDTO,
  OrderStatus,
  ORDER_STATUS_TRANSITIONS,
} from '@commerceflow/shared';

export const INITIAL_CATEGORIES: CategoryDTO[] = [
  {
    id: 1,
    name: 'Audio & Headphones',
    slug: 'audio-headphones',
    description: 'Premium noise-canceling headphones, earbuds, and studio-grade sound systems.',
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'Laptops & Computers',
    slug: 'laptops-computers',
    description: 'Ultra-portable laptops, workstation setups, and high-performance accessories.',
    image_url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80',
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'Smart Wearables',
    slug: 'smart-wearables',
    description: 'Fitness trackers, health monitoring smartwatches, and next-gen wearables.',
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: 'Mobile & Tablets',
    slug: 'mobile-tablets',
    description: 'Flagship smartphones, pro tablets, and essential mobile gear.',
    image_url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: 'Gaming Gear',
    slug: 'gaming-gear',
    description: 'Mechanical keyboards, ultra-precise mice, and immersive gaming setups.',
    image_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    created_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: 'Smart Home',
    slug: 'smart-home',
    description: 'Ambient smart lighting, AI home assistants, and automated living devices.',
    image_url: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_PRODUCTS: ProductDTO[] = [
  {
    id: 1,
    name: 'FlowSound Nova Pro Wireless Headphones',
    slug: 'flowsound-nova-pro-wireless-headphones',
    description: 'Experience pure acoustic excellence with 40mm beryllium drivers, active hybrid noise cancellation (ANC), 45-hour battery life, and ultra-plush memory foam earcups for all-day comfort.',
    price: 18999,
    stock_quantity: 14,
    sku: 'CF-AUD-001',
    category_id: 1,
    status: 'ACTIVE',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[0],
    images: [
      { id: 1, product_id: 1, image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80', is_primary: true, display_order: 0 },
      { id: 2, product_id: 1, image_url: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&auto=format&fit=crop&q=80', is_primary: false, display_order: 1 },
      { id: 3, product_id: 1, image_url: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80', is_primary: false, display_order: 2 },
    ],
  },
  {
    id: 2,
    name: 'AeroBook Titanium 16" Creator Laptop',
    slug: 'aerobook-titanium-16-creator-laptop',
    description: 'Engineered for developers and creators. Powered by an M3 Pro processor, 32GB unified RAM, 1TB ultra-fast NVMe SSD, and a breathtaking 3.2K 120Hz Mini-LED Liquid Retina display.',
    price: 149999,
    stock_quantity: 8,
    sku: 'CF-LAP-002',
    category_id: 2,
    status: 'ACTIVE',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[1],
    images: [
      { id: 4, product_id: 2, image_url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80', is_primary: true, display_order: 0 },
      { id: 5, product_id: 2, image_url: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80', is_primary: false, display_order: 1 },
    ],
  },
  {
    id: 3,
    name: 'PulseTrack Horizon Smartwatch Ultra',
    slug: 'pulsetrack-horizon-smartwatch-ultra',
    description: 'Rugged aerospace-grade titanium case with dual-frequency GPS, ECG monitor, blood oxygen tracking, 100m water resistance, and up to 72 hours of battery endurance.',
    price: 24999,
    stock_quantity: 5,
    sku: 'CF-WRB-003',
    category_id: 3,
    status: 'ACTIVE',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[2],
    images: [
      { id: 6, product_id: 3, image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80', is_primary: true, display_order: 0 },
      { id: 7, product_id: 3, image_url: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80', is_primary: false, display_order: 1 },
    ],
  },
  {
    id: 4,
    name: 'ApexPro 75% Wireless Mechanical Keyboard',
    slug: 'apexpro-75-wireless-mechanical-keyboard',
    description: 'Gasket-mounted mechanical keyboard with hot-swappable custom lubricated linear switches, CNC aluminum chassis, PBT double-shot keycaps, and tri-mode connectivity.',
    price: 11499,
    stock_quantity: 18,
    sku: 'CF-GAM-004',
    category_id: 5,
    status: 'ACTIVE',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[4],
    images: [
      { id: 8, product_id: 4, image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80', is_primary: true, display_order: 0 },
      { id: 9, product_id: 4, image_url: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&auto=format&fit=crop&q=80', is_primary: false, display_order: 1 },
    ],
  },
  {
    id: 5,
    name: 'Lumina Smart Ambient Studio Bar 2-Pack',
    slug: 'lumina-smart-ambient-studio-bar-2-pack',
    description: 'Sync your workspace with over 16 million vibrant colors and reactive sound visualizer modes. Seamlessly connects with Apple Home, Alexa, and Google Assistant.',
    price: 6999,
    stock_quantity: 2,
    sku: 'CF-SMH-005',
    category_id: 6,
    status: 'ACTIVE',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[5],
    images: [
      { id: 10, product_id: 5, image_url: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80', is_primary: true, display_order: 0 },
    ],
  },
  {
    id: 6,
    name: 'Vortex Precision 4K Wireless Gaming Mouse',
    slug: 'vortex-precision-4k-wireless-gaming-mouse',
    description: 'Ultra-lightweight 49-gram magnesium skeleton design with 26,000 DPI optical sensor, optical micro switches rated for 100M clicks, and zero-latency 4,000Hz polling rate.',
    price: 8499,
    stock_quantity: 0,
    sku: 'CF-GAM-006',
    category_id: 5,
    status: 'OUT_OF_STOCK',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[4],
    images: [
      { id: 11, product_id: 6, image_url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80', is_primary: true, display_order: 0 },
    ],
  },
  {
    id: 7,
    name: 'SoundPod Air ANC True Wireless Earbuds',
    slug: 'soundpod-air-anc-true-wireless-earbuds',
    description: 'Studio sound inside your pocket. Featuring adaptive spatial audio with dynamic head tracking, transparency mode, wireless Qi charging case, and IPX5 sweat resistance.',
    price: 9999,
    stock_quantity: 25,
    sku: 'CF-AUD-007',
    category_id: 1,
    status: 'ACTIVE',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[0],
    images: [
      { id: 12, product_id: 7, image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80', is_primary: true, display_order: 0 },
    ],
  },
  {
    id: 8,
    name: 'VisionPad Max 12.9" OLED Tablet',
    slug: 'visionpad-max-12-9-oled-tablet',
    description: 'Stunning 120Hz tandem OLED screen with stylus support, 16GB RAM, 512GB storage, quad-speaker Dolby Atmos audio, and all-day 10,000mAh battery life.',
    price: 79999,
    stock_quantity: 4,
    sku: 'CF-MOB-009',
    category_id: 4,
    status: 'ACTIVE',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[3],
    images: [
      { id: 13, product_id: 8, image_url: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80', is_primary: true, display_order: 0 },
    ],
  },
];

export const INITIAL_ORDERS: OrderDTO[] = [
  {
    id: 1,
    order_number: 'CF-058211294',
    user_id: 2,
    shipping_name: 'Rohan Sharma',
    shipping_phone: '+91 98765 43210',
    shipping_address: 'Flat 402, Skyline Residency, MG Road',
    shipping_city: 'Bengaluru',
    shipping_state: 'Karnataka',
    shipping_postal: '560001',
    subtotal: 18999,
    shipping_fee: 0,
    total_amount: 18999,
    payment_status: 'PAID',
    order_status: 'PENDING',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
    items: [
      {
        id: 1,
        order_id: 1,
        product_id: 1,
        product_name: 'FlowSound Nova Pro Wireless Headphones',
        product_sku: 'CF-AUD-001',
        product_image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
        quantity: 1,
        price: 18999,
      },
    ],
    payments: [
      {
        id: 1,
        order_id: 1,
        payment_method: 'CREDIT_CARD',
        payment_status: 'PAID',
        transaction_reference: 'TXN-9941824',
        amount: 18999,
        created_at: new Date(Date.now() - 3600000).toISOString(),
      },
    ],
  },
  {
    id: 2,
    order_number: 'CF-941827453',
    user_id: 2,
    shipping_name: 'Rohan Sharma',
    shipping_phone: '+91 98765 43210',
    shipping_address: 'Flat 402, Skyline Residency, MG Road',
    shipping_city: 'Bengaluru',
    shipping_state: 'Karnataka',
    shipping_postal: '560001',
    subtotal: 36498,
    shipping_fee: 0,
    total_amount: 36498,
    payment_status: 'PAID',
    order_status: 'CONFIRMED',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    items: [
      {
        id: 2,
        order_id: 2,
        product_id: 3,
        product_name: 'PulseTrack Horizon Smartwatch Ultra',
        product_sku: 'CF-WRB-003',
        product_image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
        quantity: 1,
        price: 24999,
      },
      {
        id: 3,
        order_id: 2,
        product_id: 4,
        product_name: 'ApexPro 75% Wireless Mechanical Keyboard',
        product_sku: 'CF-GAM-004',
        product_image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
        quantity: 1,
        price: 11499,
      },
    ],
    payments: [
      {
        id: 2,
        order_id: 2,
        payment_method: 'CREDIT_CARD',
        payment_status: 'PAID',
        transaction_reference: 'TXN-8271049',
        amount: 36498,
        created_at: new Date(Date.now() - 86400000).toISOString(),
      },
    ],
  },
];
